const AuthActions = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',

  TOKEN_NEEDS_REFRESH: 'TOKEN_NEEDS_REFRESH',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
};

export default AuthActions;
