const UserTableActions = {
  INIT_TABLE: 'INIT_TABLE',
  INIT_SUCCESS: 'INIT_SUCCESS',
  NEXT_PAGE: 'NEXT_PAGE',
  PREV_PAGE: 'PREV_PAGE',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',

  INIT_FAILURE: 'INIT_FAILURE',
  PAGINATION_FAILURE: 'PAGINATION_FAILURE',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
};

export default UserTableActions;
